.\" Copyright (c) 2014 Apple Inc. All rights reserved.
.Dd 23 April, 2014
.Dt configd_dnsinfo 8
.Os Darwin
.Sh NAME
.Nm configd_dnsinfo
.Nd System DNS Configuration Daemon
.Sh DESCRIPTION
The
.Nm
daemon is responsible for resolver configuration of the local system.
It is not intended to be invoked directly.
.Sh FILES
/etc/resolv.conf
.Sh SEE ALSO
.Xr resolver 5
.Xr configd 8
